### PR TITLE
compositor: Send mouse move event to ensure window focus.

### LINKED ISSUE #92: Focus issue with rotating input
on watches with a rotating crown (narwhal, ray/firefish) the rotating crown seems to suffer from a focus issue when opening apps. After tapping the screen after entering an application with some flickable-derived panel, the scroll wheel works fine, but it will not work until the screen is tapped. This seems to be an issue with the compositor not transferring focus correctly.

### PR DESCRIPTION
**Pull request by MagneFire**
`sendMouseWheelEvent()` doesn't ensure that the window gets focused leading to wheel events never arriving in applications until the window is hovered by means of a `sendMouseMoveEvent()` event. This works well for desktop applications but not for mobile applications where one might want to use a rotary input the moment a window is opened. This sends a `sendMouseMoveEvent()` call such that the `ensureEntered()` is called which calls the send_enter() which appears to be needed in order for wheel events to arrive (it informs the Wayland client).

This fixes https://github.com/AsteroidOS/asteroid-launcher/issues/92.

### CODE REVIEW

File: src/compositor/lipstickcompositorwindow.cpp [hunk 1]
```diff
@@ -292,6 +292,8 @@ void LipstickCompositorWindow::wheelEvent(QWheelEvent *event)
     QWaylandSurface *m_surface = surface();
     if (m_surface) {
         QWaylandSeat *inputDevice = m_surface->compositor()->seatFor(event);
+        QPointF pos(0, 0);
```
Comment (FlorentRevest) [inline src/compositor/lipstickcompositorwindow.cpp]: Could you guard this event by a check for `view != inputDevice->mouseFocus` ?https://github.com/qt/qtwayland/blob/135a3e39c349658e10329ff3988434d0d9b01ce8/src/compositor/compositor_api/qwaylandpointer.cpp#L253

My concern is that if the cursor is currently at a certain position in the window (hovering over some element for example) and the user turns the rotary input, it'd lead to the mouse moving somewhere else for no reason.

Practically speaking, this shouldn't be such a big issue on our smartwatches but I think I would sleep better at night knowing that this situation can't happen.

Also, since we are at it, it's probably worth having a short comment explaining why this is here. Even though we plan to ditch lipstick someday, I suppose it can't hurt.
